services:
    mariadb: !reset []
    mail: !reset []

    phpfpm:
        image: itkdev/php8.4-fpm:latest
        depends_on: !reset []

    nginx:
        labels:
            #      HTTPS config - uncomment to enable redirect from :80 to :443
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    # https://github.com/fathyb/html2svg
    html2svg:
        image: fathyb/html2svg
        # https://github.com/fathyb/html2svg?tab=readme-ov-file#server
        command: serve
        networks:
            - app

    markdownlint:
        image: peterdavehello/markdownlint
        profiles:
            - dev
        volumes:
            - ./:/md

    prettier:
        # Prettier does not (yet, fcf.
        # https://github.com/prettier/prettier/issues/15206) have an official
        # docker image.
        # https://hub.docker.com/r/jauderho/prettier is good candidate (cf. https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc)
        image: jauderho/prettier
        profiles:
            - dev
        volumes:
            - ./:/work
