FROM itkdev/php8.4-fpm:alpine

USER root

# https://gist.github.com/LoganGray/8aa2de1a079222d9e2ba39ecd207684e
# https://stackoverflow.com/questions/58654309/how-can-we-install-google-chrome-stable-on-alpine-image-in-dockerfile-using-dpkg
RUN apk add chromium


USER deploy
