# https://taskfile.dev

version: "3"

# https://taskfile.dev/usage/#env-files
dotenv: [".env.local", ".env"]

vars:
    # https://taskfile.dev/reference/templating/
    DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'
    COMPOSER_INSTALL_ARGUMENTS: '{{.TASK_COMPOSER_INSTALL_ARGUMENTS | default ""}}'

tasks:
    default:
        cmds:
            - task --list
        silent: true

    site:update:
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: pull
            - task: compose
              vars:
                  TASK_ARGS: up --detach --remove-orphans --build --wait
            - task: composer
              vars:
                  TASK_ARGS: install {{.COMPOSER_INSTALL_ARGUMENTS}}
            # https://symfony.com/doc/current/frontend/asset_mapper.html#serving-assets-in-dev-vs-prod
            - '[ "${APP_ENV:-}" = "prod" ] && task console -- asset-map:compile || true'
            - task: console
              vars:
                  TASK_ARGS: cache:clear
        silent: true

    site:open:
        cmds:
            - open "http://{{.SITE_URL}}"
        vars:
            SITE_URL:
                sh: task compose -- port nginx 8080
        silent: true

    console:
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm bin/console {{.TASK_ARGS}}

    compose:
        cmds:
            - "{{.DOCKER_COMPOSE}} {{.TASK_ARGS}} {{.CLI_ARGS}}"

    composer:
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm composer {{.TASK_ARGS}}
        silent: true

    coding-standards:apply:
        desc: "Apply coding standards"
        cmds:
            - task: coding-standards:assets:apply
            - task: coding-standards:composer:apply
            - task: coding-standards:markdown:apply
            - task: coding-standards:php:apply
            - task: coding-standards:twig:apply
            - task: coding-standards:yaml:apply
        silent: true

    coding-standards:check:
        desc: "Apply coding standards"
        cmds:
            - task: coding-standards:assets:check
            - task: coding-standards:composer:check
            - task: coding-standards:markdown:check
            - task: coding-standards:php:check
            - task: coding-standards:twig:check
            - task: coding-standards:yaml:check
        silent: true

    coding-standards:assets:apply:
        desc: "Apply coding standards for assets"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: run --rm prettier 'assets/**' 'html2svg/**/*.js' --write

    coding-standards:assets:check:
        desc: "Apply and check coding standards for assets"
        cmds:
            - task: coding-standards:assets:apply
            - task: compose
              vars:
                  TASK_ARGS: run --rm prettier 'assets/**' 'html2svg/**/*.js' --check

    coding-standards:composer:apply:
        desc: "Apply coding standards for composer"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm composer normalize

    coding-standards:composer:check:
        desc: "Apply and check coding standards for composer"
        cmds:
            - task: coding-standards:composer:apply
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm composer normalize --dry-run

    coding-standards:markdown:apply:
        desc: "Apply coding standards for Markdown"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: run --rm markdownlint markdownlint '**/*.md' --fix

    coding-standards:markdown:check:
        desc: "Apply and check coding standards for Markdown"
        cmds:
            - task: coding-standards:markdown:apply
            - task: compose
              vars:
                  TASK_ARGS: run --rm markdownlint markdownlint '**/*.md'

    coding-standards:php:apply:
        desc: "Apply coding standards for PHP"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: exec --env PHP_CS_FIXER_IGNORE_ENV=1 phpfpm vendor/bin/php-cs-fixer fix
        silent: true

    coding-standards:php:check:
        desc: "Apply and check coding standards for PHP"
        cmds:
            - task: coding-standards:php:apply
            - task: compose
              vars:
                  TASK_ARGS: exec --env PHP_CS_FIXER_IGNORE_ENV=1 phpfpm vendor/bin/php-cs-fixer check
        silent: true

    coding-standards:twig:apply:
        desc: "Apply coding standards for Twig"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm vendor/bin/twig-cs-fixer fix
        silent: true

    coding-standards:twig:check:
        desc: "Apply and check coding standards for Twig"
        cmds:
            - task: coding-standards:twig:apply
            - task: compose
              vars:
                  TASK_ARGS: exec phpfpm vendor/bin/twig-cs-fixer lint
        silent: true

    coding-standards:yaml:apply:
        desc: "Apply coding standards for YAML"
        cmds:
            - task: compose
              vars:
                  TASK_ARGS: run --rm prettier '**/*.{yml,yaml}' --write

    coding-standards:yaml:check:
        desc: "Apply and check coding standards for YAML"
        cmds:
            - task: coding-standards:yaml:apply
            - task: compose
              vars:
                  TASK_ARGS: run --rm prettier '**/*.{yml,yaml}' --check

    translations:extract:
        cmds:
            # We need a translation from en to en (!) (without prefix) to be able to process placeholders in en.
            - "DEFAULT_LOCALE=en task console -- translation:extract --clean --force en --prefix=''"
            - "DEFAULT_LOCALE=en task console -- translation:extract --clean --force da"
            # Mark default translations (prefixed with `__`) as “Needs work” in Danish translations
            - sed --in-place='' 's/<target>__/<target state=\"needs-l10n\">__/' translations/*.da.*xlf
        silent: true
